### ISSUE TITLE
Tech Prerequisites code chunk - no plot output

### ISSUE THREAD

**Issue by AyeMiranda** [daroczig/CEU-DV2#1]
Hi, I tried running the following code:
```
install.packages(c('ggplot2', 'gganimate', 'transformr'))
library(ggplot2)
library(gganimate)
ggplot(diamonds, aes(cut)) + geom_bar() +
    transition_states(color, state_length = 0.1)
```
I didn't get errors or warning messages but there is no plot output (although 100 .png plots appeared on my directory)
I ran `ggplot(diamonds, aes(cut)) + geom_bar() +  transition_states(color, state_length = 0.1)`  again, still no plot but now I got this warning message:
`Warning message: file_renderer failed to copy frames to the destination directory `

Maybe I'm missing something? I'm using Mac & R version 3.6.1

Thanks and see you next week!

Arielle

**Comment by daroczig** [comment]
Can you try installing the `gifski` package and then restart R/RStudio and give it a try again?

If that doesn't help, maybe look at the permissions of `/var/folders` and make sure you can write there.

Please report back with your findings (or struggles) so that others can learn from that as well.

**Comment by kristofrabay** [comment]
Had the same issue (didn't think that the downloaded pngs with the different states were an issue) now it's working fine for me, if seeing an always motioning chart like a gif in the plot area is what I'm supposed to see.

**Comment by daroczig** [comment]
> if seeing an always motioning chart like a gif in the plot area is what I'm supposed to see

yeah, an animated gif should show up in the "viewer" (and not in the "plots" panel)

**Comment by kristofrabay** [comment]
Viewer one it is, my bad

**Comment by AyeMiranda** [comment]
> Can you try installing the `gifski` package and then restart R/RStudio and give it a try again?

Now it works after installing and loading `gifski` package. Thanks!
