### ISSUE TITLE
Errors running the R code chunk

### ISSUE THREAD

**Issue by manilasaroyan** [daroczig/CEU-DV2#2]
Hi @daroczig ,

I am getting these errors when running the code chunk. Can you please look at it?

<img width="739" alt="Screen Shot 2020-01-08 at 11 20 41 AM" src="https://user-images.githubusercontent.com/54810342/71970654-617e8f00-3209-11ea-817e-909663e03fa2.png">

**Comment by daroczig** [comment]
Pls install the `png` package as well and try again.

--
Sent from a mobile phone with an annoying input interface, pls excuse my
brevity/spelling issues.

**Comment by manilasaroyan** [comment]
It worked! Thanks
