### ISSUE TITLE
decimals ( q3)

### ISSUE THREAD

**Issue by starka1986** [daroczig/CEU-DV2#3]
pls remove if I shouldn't be posting solution attempts here.
trying to get the decimals for the avg ratings, and have tried 4 ways already. 
Not sure about hw eval ( are attempts evaluated at all or only right solution? ) and don't want to waste a lot of time.
Are any of the below the right track? thank you
```{r}
formatRound(hotels_sub4,columns,digits = 2,interval = 3,mark = ",", dec.mark = getOption("OutDec")) # not working
hotels_sub4[,mean(rating)]
setNumericRounding(2) # not working
hotels_sub5 <- format(hotels_sub4, digits = 2) # not what I need
hotels_sub5[,mean(rating)] # so won't work like this
# last attempt:
hotels_sub4[is.num] <- lapply(hotels_sub4[is.num], round, 2) #doesn't work either
```

**Comment by daroczig** [comment]
the last attempt is the closest I think, in the means of what rounding function to use, but I don't think you need any `lapply` there. I hope this helps, and I'm closing the ticket, but if you need more help, please check with Misi and schedule a meeting at the office hours
